server:
  port: 8084
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/IVANMAMANI2003/microservicios_DAD_2023_C5.git
          search-paths: config-data
          username: ivanmamani
          password: Ivan74178089
          default-label: main
  security:
    user:
      name: root
      password: s3cr3t
